<?php
/**
 * Copyright 2014 HappyFox.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
?>

<?php if($this->isHappFoxDashboard() || Mage::getStoreConfig('happyfox/extension_settings/display_tickets')): ?>
	<?php if($this->isHappFoxDashboard()): ?>
		<div class="content-header">
			<table cellspacing="0">
				<tr>
					<td>
						<h3 class="head-dashboard">HappyFox - Dashboard</h3>
					</td>
				</tr>
			</table>
		</div>
	<?php endif; ?>
	<div class="happyfox-dashboard-container">
		<?php echo $this->getChildHtml('happyfox_dashboard_grids'); ?>
		<div id="happyfox_tickets_grid_tab_content">
		</div>
	</div>
	<?php echo $this->getChildHtml('happyfox_dashboard_empty'); ?>
<?php endif;?>
